### ISSUE TITLE
cave_miner not working

### ISSUE THREAD

**Issue by amlamarra** [Antonin-Deniau/cave_miner#3]
I just tried using cave_miner and I get the following:

```
$ cave_miner search write4 

    /========\
   /    ||    \
        ||
        ||
        ||
   CAVE || MINER
  
[*] Starting cave mining process...
    Searching for bytes: 0x00...

Traceback (most recent call last):
  File "/usr/bin/cave_miner", line 11, in <module>
    load_entry_point('cave-miner==1.7', 'console_scripts', 'cave_miner')()
  File "/usr/lib/python2.7/site-packages/cave_miner/main.py", line 37, in main
    if CONTINUE: search(args["<file_name>"], args["--size"], args["--bytes"])
  File "/usr/lib/python2.7/site-packages/cave_miner/search.py", line 121, in search
    detect_type(filename, parse_int(cavesize), _bytes)
  File "/usr/lib/python2.7/site-packages/cave_miner/search.py", line 111, in detect_type
    elif data[0x0:0x4] == elf:   search_elf(filename, cavesize, _bytes)
  File "/usr/lib/python2.7/site-packages/cave_miner/search.py", line 97, in search_elf
    g = Elf.from_file(filename)
  File "/usr/lib/python2.7/site-packages/kaitaistruct.py", line 37, in from_file
    return cls(KaitaiStream(f))
  File "/usr/lib/python2.7/site-packages/cave_miner/formats/elf.py", line 113, in __init__
    self._read()
  File "/usr/lib/python2.7/site-packages/cave_miner/formats/elf.py", line 117, in _read
    self.bits = self._root.Bits(self._io.read_u1())
  File "/usr/lib/python2.7/site-packages/enum.py", line 199, in __init__
    raise EnumBadKeyError(key)
enum.EnumBadKeyError: Enumeration keys must be strings: 2
```

Same results for any binary.

I'm running Arch Linux x64.

**Comment by epi052** [comment]
not sure if you care anymore or not, but i had the same problem

i installed the wrong enum package

try removing your current enum package and runnning 

`pip install enum34`
