### ISSUE TITLE
Error when I run cave_miner

### ISSUE THREAD

**Issue by SpikeI** [Antonin-Deniau/cave_miner#5]
Traceback (most recent call last):
  File "/bin/cave_miner", line 9, in <module>
    load_entry_point('cave-miner==1.8.0', 'console_scripts', 'cave_miner')()
  File "build/bdist.linux-x86_64/egg/cave_miner/main.py", line 43, in main
  File "build/bdist.linux-x86_64/egg/cave_miner/search.py", line 138, in search
  File "build/bdist.linux-x86_64/egg/cave_miner/search.py", line 128, in detect_type
  File "build/bdist.linux-x86_64/egg/cave_miner/search.py", line 118, in search_elf
  File "build/bdist.linux-x86_64/egg/cave_miner/formats/elf.py", line 385, in body
  File "build/bdist.linux-x86_64/egg/kaitaistruct.py", line 242, in read_bytes
EOFError: requested 13648 bytes, but got only 9828 bytes

Is that a bug?

**Comment by SpikeI** [comment]
I run it in ubuntu 16.04, 

> cave_miner search apache2
