### ISSUE TITLE
cave_miner throwing an error

### ISSUE THREAD

**Issue by bhanutheja17** [Antonin-Deniau/cave_miner#6]
I see the following error while running cave_miner

:\Python38>cave_miner.exe search
Traceback (most recent call last):
  File "C:\Python38\Scripts\cave_miner-script.py", line 11, in <module>
    load_entry_point('cave-miner==1.8.0', 'console_scripts', 'cave_miner')()
  File "c:\python38\lib\site-packages\cave_miner-1.8.0-py3.8.egg\cave_miner\main.py", line 34, in main
  File "c:\python38\lib\site-packages\cave_miner-1.8.0-py3.8.egg\cave_miner\main.py", line 31, in print_banner
NameError: name 'color' is not defined

**Comment by vikramRooT** [comment]
bro answer?
